{%raw%}{% set data = load_setup_py_data() %}{%endraw%}

package:
    name: {{cookiecutter.package_name}}
    version: {%raw%}{{ data.get('version') }}{%endraw%}

source:
    path: .

{%raw%}
build:
    script: "{{ PYTHON }} -m pip install . --no-deps"
    noarch: python
    number: {{ GIT_DESCRIBE_NUMBER }}
{%endraw%}

requirements:
    host:
        - python
        - pip
    run:
        - python >=3.6

test:
    imports:
        - {{cookiecutter.package_name}}
    requires:
        - pytest
        - pytest-cov
    files:
        - test
        - src
    script_env:
        - TEST_OUTPUT
    commands:
        - py.test --cov=src --junit-xml=${TEST_OUTPUT:-.}/pytest/junit.xml --cov-report=xml:${TEST_OUTPUT:-.}/cov/coverage.xml

